version: "3"

services:
  handle-instance:
    image: git.openlab.itu.int/aims/lhs:latest
    container_name: handle-instance
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./instance-data:/home/lhs/data
    ports:
      - 2641:2641/tcp
      - 2641:2641/udp
      - 8000:8000/tcp

